### PR TITLE
Raname Custom Labels File

### PR DESCRIPTION
**Pull request by wimvelzeboer**
There seems to be installation problems when the filename is not matching "CustomLabels.labels-meta.xml".

Resolves issue #357 

---
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/358)

### CODE REVIEW

**Comment by ImJohnMDaniel** [comment]
@wimvelzeboer What issues are you seeing and what has changed that would bring these issues about now?

**Comment by daveespo** [comment]
@wimvelzeboer  -- I'm not facing a problem doing a `sfdx force:source:push` with this repo prior to your changes.

I see this and it looks like it's been merged and I would expect it to be in next week's CLI build:

https://github.com/forcedotcom/source-deploy-retrieve/pull/427

**Comment by wimvelzeboer** [comment]
@ImJohnMDaniel @daveespo Indeed, it seems to be an issue in the SFDX CLI for the force:source:deploy command. 
So, we can either wait until they fix it or rename the CustomLabels file.

**Comment by ImJohnMDaniel** [comment]
@wimvelzeboer -- let's wait for the CLI fix.  The custom labels file was deliberately created like this for the use case when developers include this repo into their own larger code repo.  Having the custom labels file uniquely named avoids a collision of multiple "CustomLabels" files.

Unless there is no objections, I would like to cancel this PR.

**Comment by daveespo** [comment]
I'm in agreement; this week's CLI release will have a fix for the Custom Labels regression:

https://github.com/forcedotcom/cli/tree/main/releasenotes#aug-26-2021

**Pull request closed without merging**
