### PR TITLE
Add register empty recycle bin to UnitOfWork

### PR DESCRIPTION
**Pull request by wimvelzeboer**
This will add the option to empty the recycle bin via the UnitOfWork.
It adds these methods:
`void registerPermanentlyDeleted(SObject record);`
`void registerPermanentlyDeleted(List<SObject> records);`
`void registerEmptyRecycleBin(SObject record);`
`void registerEmptyRecycleBin(List<SObject> records);`

This will resolve issue #238

### CODE REVIEW

**Comment by afawcett** [comment]
So looks like we need some tests for this change. Also I am getting some deployment errors for this... looks like more work to do to reflect this change elsewhere in the library. 
```TYPE   FILE                                   NAME                   PROBLEM
─────  ─────────────────────────────────────  ─────────────────────  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error  src/classes/fflib_ApplicationTest.cls  fflib_ApplicationTest  Class fflib_ApplicationTest.CustomDML must implement the method: void fflib_SObjectUnitOfWork.IDML.emptyRecycleBin(List<SObject>)
Error  src/classes/fflib_SObjectMocks.cls     fflib_SObjectMocks     Class fflib_SObjectMocks.SObjectUnitOfWork must implement the method: void fflib_ISObjectUnitOfWork.registerEmptyRecycleBin(SObject)
Error  src/classes/fflib_SObjectMocks.cls     fflib_SObjectMocks     Class fflib_SObjectMocks.SObjectUnitOfWork must implement the method: void fflib_ISObjectUnitOfWork.registerEmptyRecycleBin(List<SObject>)
Error  src/classes/fflib_SObjectMocks.cls     fflib_SObjectMocks     Class fflib_SObjectMocks.SObjectUnitOfWork must implement the method: void fflib_ISObjectUnitOfWork.registerPermanentlyDeleted(List<SObject>)
Error  src/classes/fflib_SObjectMocks.cls     fflib_SObjectMocks     Class fflib_SObjectMocks.SObjectUnitOfWork must implement the method: void fflib_ISObjectUnitOfWork.registerPermanentlyDeleted(SObject)```

**Comment by ImJohnMDaniel** [comment]
@wimvelzeboer, The final reviews on this issue are pending resolution to unit test failures that @afawcett mentioned [here](https://github.com/apex-enterprise-patterns/fflib-apex-common/pull/248#issuecomment-569345582).  Please let us know when you have these sorted. Cheers!

**Comment by wimvelzeboer** [comment]
@afawcett @ImJohnMDaniel the failures are now fixed, can you please review this PR?

**Comment by ImJohnMDaniel** [comment]
@wimvelzeboer -- changes look good!

**Pull request merged**
