### PR TITLE
Features/fix spring 21

### PR DESCRIPTION
**Pull request by brandonmikeska**
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/320)

### CODE REVIEW

**Comment by ImJohnMDaniel** [comment]
@brandonmikeska -- Can you elaborate in the description of this Pull Request exactly what the issue was and a summary of the fix please?

**Comment by ImJohnMDaniel** [comment]
Nevermind -- I see you closed it.

**Comment by anuragoyar** [comment]
# Potential Risks and Suggestions

1.  
File: sfdx-source/apex-common/main/classes/fflib_QueryFactory.cls  
Code Snippet: //traversing FK relationship(s)
    List<String> fieldPath = new List<String>();
    Schema.sObjectType lastSObjectType = table;
    Iterator<String> i = fieldName.split('\\.').iterator();
    while (i.hasNext()) {
      String field = i.next();
      Schema.SObjectField token = fflib_SObjectDescribe.getDescribe(lastSObjectType)
        .getField(field.toLowerCase());
      DescribeFieldResult tokenDescribe = token != null ? token.getDescribe() : null;

      if (token != null && enforceFLS) {
        fflib_SecurityUtils.checkFieldIsReadable(lastSObjectType, token);
      }  
Comment: This code appears to be a fragment that was added in the middle of an existing method without proper integration. It doesn't have a method signature or return statement, which will likely cause compilation errors. This needs to be properly integrated into the existing method structure.

2.  
File: sfdx-source/apex-common/main/classes/fflib_SecurityUtils.cls  
Code Snippet: Multiple duplicate method implementations like checkObjectIsReadable, checkObjectIsUpdateable, etc.  
Comment: There are duplicate implementations of several methods in this class. For example, checkObjectIsReadable appears twice with different closing braces. This will cause compilation errors and needs to be resolved before deployment.

3.  
File: sfdx-source/apex-common/test/classes/fflib_SObjectUnitOfWorkTest.cls  
Code Snippet: assertEvents method implementation is incomplete  
Comment: The assertEvents method appears to be missing its opening implementation but has closing code. This will cause compilation errors in test classes.

## Summary:

This PR contains significant changes to the FFLib Apex Common library, a foundational framework for Salesforce development. The changes include:

1. **Code Formatting**: Most changes appear to be code formatting improvements, including consistent indentation, spacing, and line breaks.

2. **Project Configuration Updates**:
   - Added `.prettierrc` configuration file for consistent code formatting
   - Updated `sfdx-project.json` with package version information and dependencies
   - Updated README.md with improved formatting and additional deployment instructions

3. **Code Improvements**:
   - Fixed several method implementations in various classes
   - Added new functionality in some classes like `fflib_QueryFactory`
   - Improved code organization and readability

4. **Potential Issues**:
   - Several code fragments appear to be incomplete or improperly integrated
   - Duplicate method implementations in `fflib_SecurityUtils.cls`
   - Incomplete test method in `fflib_SObjectUnitOfWorkTest.cls`

## Risks and Concerns:

1. **Compilation Errors**: The PR contains several code fragments that appear incomplete or improperly integrated, which will likely cause compilation errors.

2. **Test Coverage**: While the changes include updates to test classes, the incomplete implementation of the `assertEvents` method in `fflib_SObjectUnitOfWorkTest.cls` may cause test failures.

3. **Dependency Management**: The PR updates the package dependencies in `sfdx-project.json`, but it's unclear if all required dependencies are properly configured.

4. **Backward Compatibility**: The FFLib Apex Common library is likely used by many components in the org, and changes to its core functionality could have widespread impacts.

## Recommendations:

1. **Fix Compilation Issues**: Address the incomplete code fragments and duplicate method implementations before deployment.

2. **Comprehensive Testing**: Ensure all tests pass after fixing the compilation issues. Consider adding additional tests for any new functionality.

3. **Staged Deployment**: Deploy to a sandbox environment first to verify that all components function correctly with the updated library.

4. **Rollback Plan**: Have a clear rollback plan in case issues are discovered after deployment, including a backup of the current implementation.

5. **Documentation**: Update any internal documentation to reflect changes in the library's behavior or API.

This PR contains significant improvements to the FFLib Apex Common library, but the identified issues need to be addressed before it can be safely deployed to production. The changes are primarily formatting and code organization, with some functional improvements, but the incomplete code fragments and duplicate method implementations pose a high risk of compilation errors.

**Comment by anuragoyar** [comment]
# Potential Risks and Suggestions

1.  
File: sfdx-source/apex-common/main/classes/fflib_QueryFactory.cls  
Code Snippet: `//traversing FK relationship(s)
    List<String> fieldPath = new List<String>();
    Schema.sObjectType lastSObjectType = table;
    Iterator<String> i = fieldName.split('\\.').iterator();
    while (i.hasNext()) {
      String field = i.next();
      Schema.SObjectField token = fflib_SObjectDescribe.getDescribe(lastSObjectType)
        .getField(field.toLowerCase());
      DescribeFieldResult tokenDescribe = token != null ? token.getDescribe() : null;`  
Comment: There appears to be a code block that's been added in the middle of a method without proper context or completion. This could lead to runtime errors as the code seems to be incomplete and might not be properly integrated with the surrounding method.

2.  
File: sfdx-source/apex-common/main/classes/fflib_SObjectDescribe.cls  
Code Snippet: `public Schema.SObjectField getNameField() {
    if (nameField == null) {
      for (Schema.SObjectField field : wrappedFields.values()) {
        if (field.getDescribe().isNameField()) {
          nameField = field;
          break;
        }
      }
    }
    return nameField;
  }`  
Comment: The `nameField` instance variable is not declared in the visible code, which could lead to compilation errors. Ensure this variable is properly declared in the class.

3.  
File: sfdx-source/apex-common/test/classes/fflib_SObjectUnitOfWorkTest.cls  
Code Snippet: `/**
     * Assert that actual events exactly match expected events (size, order and name)
     * and types match expected types
     */
    private static void assertEvents(List<String> expectedEvents, List<String> actualEvents, Set<Schema.SObjectType> expectedTypes, Set<Schema.SObjectType> actualTypes)
    {
        // assert that events match
        System.assertEquals(expectedEvents.size(), actualEvents.size(), 'events size');
        for (Integer i = 0; i < expectedEvents.size(); i++)
        {
            System.assertEquals(expectedEvents[i], actualEvents[i], String.format('Event {0} was not fired in order expected.', new List<String> { expectedEvents[i] }));
        }`  
Comment: The `assertEvents` method appears to be incomplete - the method opening is present but the closing bracket is missing. This will cause compilation errors.

4.  
File: sfdx-source/apex-common/main/classes/fflib_SecurityUtils.cls  
Code Snippet: Multiple duplicate method implementations and incomplete code blocks  
Comment: There appear to be duplicate implementations of methods like `checkObjectIsReadable` and `checkObjectIsUpdateable` with incomplete code blocks. This will cause compilation errors and unpredictable behavior.

5.  
File: sfdx-project.json  
Code Snippet: `"packageAliases": {
        "Apex Enterprise Patterns": "0Ho0y000000PAtGCAW",
        "Apex Enterprise Patterns@0.1.0-1": "04t0y000000u3k9AAA",
        "Apex Enterprise Patterns@0.1.0-2": "04t0y000000u3kOAAQ"
    }`  
Comment: The package configuration has been updated to include package versions. Ensure these package IDs are correct and accessible in the target org before deployment.

## Summary:

This PR contains significant changes to the FFLib Apex Common library, including:

1. **Code Formatting Changes**: Most files have been reformatted with consistent indentation and spacing, which accounts for the majority of the changes.

2. **Package Configuration Updates**: 
   - Added package version information in sfdx-project.json
   - Added dependency on ApexMocks Framework
   - Added deployment instructions in README.md

3. **Code Additions and Modifications**:
   - Added new methods to several classes including fflib_SObjectDescribe, fflib_QueryFactory
   - Modified method implementations in fflib_SObjectDomain, fflib_SObjectU

**Comment by anuragoyar** [comment]
# Potential Risks and Suggestions

1.  
File: sfdx-source/apex-common/main/classes/fflib_QueryFactory.cls  
Code Snippet: ```java
//traversing FK relationship(s)
List<String> fieldPath = new List<String>();
Schema.sObjectType lastSObjectType = table;
Iterator<String> i = fieldName.split('\\.').iterator();
while (i.hasNext()) {
  String field = i.next();
  Schema.SObjectField token = fflib_SObjectDescribe.getDescribe(lastSObjectType)
    .getField(field.toLowerCase());
  DescribeFieldResult tokenDescribe = token != null ? token.getDescribe() : null;
```  
Comment: This code appears to be a partial implementation that's not properly integrated with the rest of the class. It's defined outside of any method and would cause compilation errors. It should be moved into an appropriate method or removed.

2.  
File: sfdx-source/apex-common/main/classes/fflib_SObjectDescribe.cls  
Code Snippet: ```java
public Schema.SObjectField getNameField() {
  if (nameField == null) {
    for (Schema.SObjectField field : wrappedFields.values()) {
      if (field.getDescribe().isNameField()) {
        nameField = field;
        break;
      }
    }
  }
  return nameField;
}
```  
Comment: This method is added but the `nameField` instance variable doesn't appear to be declared in the class. This will cause compilation errors. Ensure the variable is properly declared.

3.  
File: sfdx-source/apex-common/test/classes/fflib_SObjectUnitOfWorkTest.cls  
Code Snippet: ```java
/**
 * Assert that actual events exactly match expected events (size, order and name)
 * and types match expected types
 */
private static void assertEvents(List<String> expectedEvents, List<String> actualEvents, Set<Schema.SObjectType> expectedTypes, Set<Schema.SObjectType> actualTypes)
```  
Comment: The method implementation is incomplete. The first part of the method that checks events is missing, but the code still references variables from it. This will cause test failures.

4.  
File: sfdx-source/apex-common/main/classes/fflib_SecurityUtils.cls  
Code Snippet: Multiple closing braces `}` without matching opening braces  
Comment: There are several instances of unmatched closing braces in this file that will cause compilation errors. The code structure needs to be fixed to ensure proper method and class definitions.

5.  
File: sfdx-source/apex-common/main/classes/fflib_SObjectSelector.cls  
Code Snippet: ```java
/**
 * Adds the selectors fields to the given QueryFactory using the given relationship path as a prefix
 *
 * // TODO: This should be consistant (ideally) with configureQueryFactory below
 **/
public void configureQueryFactoryFields(
  fflib_QueryFactory queryFactory,
  String relationshipFieldPath
) {
```  
Comment: This method is added but appears to duplicate existing functionality. Consider consolidating with the existing method to avoid confusion and potential inconsistencies.

## Summary:

This PR contains significant changes to the Apex Enterprise Patterns library, primarily focused on code formatting and some functional enhancements. The changes include:

1. **Code Formatting**: Most files have been reformatted with consistent indentation, spacing, and line breaks. This appears to be the primary purpose of the PR.

2. **Configuration Files**:
   - Added `.prettierrc` configuration file for consistent code formatting
   - Updated `sfdx-project.json` with package configuration and dependencies
   - Updated `README.md` with deployment instructions

3. **Functional Changes**:
   - Added new methods to several classes including `fflib_SObjectDescribe`, `fflib_QueryFactory`
   - Modified method implementations in `fflib_SObjectDomain`, `fflib_SObjectSelector`
   - Fixed some existing bugs and improved code structure

4. **Potential Issues**:
   - Several code fragments appear incomplete or improperly integrated
   - Some methods are added without proper variable declarations
   - There are unmatched braces in some files that will cause compilation errors

**Comment by anuragoyar** [comment]
# Potential Risks and Suggestions

1.  
File: sfdx-source/apex-common/main/classes/fflib_QueryFactory.cls  
Code Snippet: `//traversing FK relationship(s)
    List<String> fieldPath = new List<String>();
    Schema.sObjectType lastSObjectType = table;
    Iterator<String> i = fieldName.split('\\.').iterator();
    while (i.hasNext()) {
      String field = i.next();
      Schema.SObjectField token = fflib_SObjectDescribe.getDescribe(lastSObjectType)
        .getField(field.toLowerCase());
      DescribeFieldResult tokenDescribe = token != null ? token.getDescribe() : null;`  
Comment: There appears to be a code fragment that's not properly integrated into a method. This code block is floating in the middle of the class without being part of any method definition, which will cause compilation errors.

2.  
File: sfdx-source/apex-common/main/classes/fflib_SObjectDescribe.cls  
Code Snippet: `public Schema.SObjectField getNameField() {
    if (nameField == null) {
      for (Schema.SObjectField field : wrappedFields.values()) {
        if (field.getDescribe().isNameField()) {
          nameField = field;
          break;
        }
      }
    }
    return nameField;
  }`  
Comment: The `nameField` property is not declared in the class, which will cause a compilation error. Make sure to add a private Schema.SObjectField nameField; declaration to the class.

3.  
File: sfdx-source/apex-common/test/classes/fflib_SObjectUnitOfWorkTest.cls  
Code Snippet: `/**
     * Assert that actual events exactly match expected events (size, order and name)
     * and types match expected types
     */
    private static void assertEvents(List<String> expectedEvents, List<String> actualEvents, Set<Schema.SObjectType> expectedTypes, Set<Schema.SObjectType> actualTypes)
    {
        // assert that events match
        System.assertEquals(expectedEvents.size(), actualEvents.size(), 'events size');
        for (Integer i = 0; i < expectedEvents.size(); i++)
        {
            System.assertEquals(expectedEvents[i], actualEvents[i], String.format('Event {0} was not fired in order expected.', new List<String> { expectedEvents[i] }));
        }`  
Comment: The `assertEvents` method appears to be incomplete. The method opening is present but the closing bracket is missing, and there's code outside of any method that seems to be part of this method. This will cause compilation errors.

4.  
File: sfdx-source/apex-common/main/classes/fflib_SecurityUtils.cls  
Code Snippet: Multiple duplicate method closings like `}` at lines 283, 296, and 313  
Comment: There are several standalone closing braces in the file that don't match with opening braces, suggesting incomplete or improperly formatted methods. This will cause compilation errors.

5.  
File: sfdx-source/apex-common/test/classes/fflib_SecurityUtilsTest.cls  
Code Snippet: `@isTest
	static void readonly_objectAndField_access() {
		User testUser = setupTestUser('Read Only');
		System.runAs(testUser){`  
Comment: This test method appears to be incomplete with missing closing braces. The method structure is not properly closed, which will cause compilation errors.

## Summary:

This pull request contains significant changes to the Apex Enterprise Patterns library, primarily focusing on code formatting and some functional enhancements. The changes span across multiple files including:

1. **Code Formatting**: Most changes are related to code formatting - indentation, spacing, and line breaks have been standardized across the codebase.

2. **Configuration Files**: Added a `.prettierrc` file for consistent code formatting and updated the `sfdx-project.json` with package configuration.

3. **README Updates**: Significant updates to the README.md file, including new sections on how to contribute, deploy, and install dependencies.

4. **Apex Class Modifications**: Several Apex classes have been modified with both formatting changes and some functional additions:
   - Added methods

**Comment by anuragoyar** [comment]
Error processing review: Error code: 429 - {'type': 'error', 'error': {'type': 'rate_limit_error', 'message': 'This request would exceed the rate limit for your organization (0f0c4b07-b389-43fd-a788-f46e22116c4c) of 40,000 input tokens per minute. For details, refer to: https://docs.anthropic.com/en/api/rate-limits. You can see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase.'}}. Please try again or contact support.

**Comment by anuragoyar** [comment]
# Potential Risks and Suggestions

1.  
File: sfdx-source/apex-common/main/classes/fflib_QueryFactory.cls  
Code Snippet: `//traversing FK relationship(s)
List<String> fieldPath = new List<String>();
Schema.sObjectType lastSObjectType = table;
Iterator<String> i = fieldName.split('\\.').iterator();
while (i.hasNext()) {
  String field = i.next();
  Schema.SObjectField token = fflib_SObjectDescribe.getDescribe(lastSObjectType)
    .getField(field.toLowerCase());
  DescribeFieldResult tokenDescribe = token != null ? token.getDescribe() : null;`  
Comment: There appears to be a code fragment that's not properly integrated into a method. This code block starts in the middle of the file without being enclosed in a method, which will cause compilation errors. It should be part of a method implementation.

2.  
File: sfdx-source/apex-common/main/classes/fflib_SObjectDescribe.cls  
Code Snippet: `public Schema.SObjectField getNameField() {
  if (nameField == null) {
    for (Schema.SObjectField field : wrappedFields.values()) {
      if (field.getDescribe().isNameField()) {
        nameField = field;
        break;
      }
    }
  }
  return nameField;
}`  
Comment: This method is added but the `nameField` class variable doesn't appear to be declared in the visible code. Make sure to add a private Schema.SObjectField nameField; declaration to the class.

3.  
File: sfdx-source/apex-common/test/classes/fflib_SObjectUnitOfWorkTest.cls  
Code Snippet: `/**
     * Assert that actual events exactly match expected events (size, order and name)
     * and types match expected types
     */
    private static void assertEvents(List<String> expectedEvents, List<String> actualEvents, Set<Schema.SObjectType> expectedTypes, Set<Schema.SObjectType> actualTypes)
    {
        // assert that events match
        System.assertEquals(expectedEvents.size(), actualEvents.size(), 'events size');
        for (Integer i = 0; i < expectedEvents.size(); i++)
        {
            System.assertEquals(expectedEvents[i], actualEvents[i], String.format('Event {0} was not fired in order expected.', new List<String> { expectedEvents[i] }));
        }`  
Comment: The `assertEvents` method appears to be incomplete. The method's opening code is present, but the closing bracket is missing, and there's code outside the method that seems to be part of it. This will cause compilation errors.

4.  
File: sfdx-source/apex-common/test/classes/fflib_SecurityUtilsTest.cls  
Code Snippet: `@isTest
	static void readonly_objectAndField_access() {
		User testUser = setupTestUser('Read Only');
		System.runAs(testUser){
			{
				fflib_SecurityUtils.SecurityException ex;
				try{
					fflib_SecurityUtils.checkInsert(
						Account.SObjectType,
						new List<String>{
							'Name',
							'Type',
							'ownerId'
						}
					);`  
Comment: There are several methods in this test class that have unbalanced brackets, which will cause compilation errors. The indentation suggests proper nesting, but the actual code has missing closing brackets.

5.  
File: sfdx-project.json  
Code Snippet: `"packageAliases": {
        "Apex Enterprise Patterns": "0Ho0y000000PAtGCAW",
        "Apex Enterprise Patterns@0.1.0-1": "04t0y000000u3k9AAA",
        "Apex Enterprise Patterns@0.1.0-2": "04t0y000000u3kOAAQ"
    }`  
Comment: The package configuration has been updated to include package versions and dependencies. Ensure that the referenced package "ApexMocks Framework" with ID "04t0y000000u3k4AAA" is available in the target org before deployment.

## Summary:

This PR

**Comment by anuragoyar** [comment]
Error processing review: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Please try again or contact support.

**Comment by anuragoyar** [comment]
Error processing review: 

You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
. Please try again or contact support.

**Comment by anuragoyar** [comment]
Error processing review: Request too large for gpt-4o in organization org-VIAikIB4Wf9EvMo8keTslctf on tokens per min (TPM): Limit 30000, Requested 116856. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.. Please try again or contact support.

**Comment by anuragoyar** [comment]
Error processing review: Request too large for gpt-4o in organization org-VIAikIB4Wf9EvMo8keTslctf on tokens per min (TPM): Limit 30000, Requested 116856. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.. Please try again or contact support.

**Comment by anuragoyar** [comment]
Error processing review: Request too large for gpt-4o in organization org-VIAikIB4Wf9EvMo8keTslctf on tokens per min (TPM): Limit 30000, Requested 116856. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.. Please try again or contact support.

**Pull request closed without merging**
