### PR TITLE
Update api version to 56.0 and test classes to use new Assert class

### PR DESCRIPTION
**Pull request by chazwatkins**
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/436)

### CODE REVIEW

**Comment by ImJohnMDaniel** [comment]
G'day @chazwatkins -- Just wanted to say again thank you very much for this PR. There is a lot that you updated and it is very much appreciated. Cheers!

**Review by ImJohnMDaniel — COMMENTED** [review]
G'day @chazwatkins.  I noticed that `fflib_SObjectDomain.TestSObjectStatefulDomain` and `fflib_SObjectDomain.TestSObjectDomain` each have an assertion in the old style.  Was this deliberate?

**Comment by ImJohnMDaniel** [comment]
Also, @chazwatkins, will you be updating the class xml files to v56.0?  If not, no worries.  I can definitely do it.  I just didn't want to double up on the work. 

Thanks again!!

**Comment by chazwatkins** [comment]
Since I was updating all the repos, I managed to forget to do the xml files on this one.  I'll do this now.

**Comment by chazwatkins** [comment]
The xml files are now all 56.0

**Comment by chazwatkins** [comment]
> G'day @chazwatkins. I noticed that `fflib_SObjectDomain.TestSObjectStatefulDomain` and `fflib_SObjectDomain.TestSObjectDomain` each have an assertion in the old style. Was this deliberate?

@ImJohnMDaniel It wasn't.  I'll check on them and submit the update

**Comment by chazwatkins** [comment]
> > G'day @chazwatkins. I noticed that `fflib_SObjectDomain.TestSObjectStatefulDomain` and `fflib_SObjectDomain.TestSObjectDomain` each have an assertion in the old style. Was this deliberate?
> 
> @ImJohnMDaniel It wasn't. I'll check on them and submit the update

`fflib_SObjectDomain.TestSObjectStatefulDomain` and `fflib_SObjectDomain.TestSObjectDomain` are updated to use System.Assert.areEqual now

**Review by ImJohnMDaniel — APPROVED** [review]

**Review by stohn777 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/436)* status: 0 of 40 files reviewed, 1 unresolved discussion (waiting on @chazwatkins and @daveespo)

___
*[`sfdx-source/apex-common/test/classes/fflib_SObjectDescribeTest.cls` line 49 at r3](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/436#-NIUHpU--9Q6YpjJw6QQ:-NIUHpU--9Q6YpjJw6QR:b8u6t83) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/7dad734dc470ab770591b7633f8afba92d7078c0/sfdx-source/apex-common/test/classes/fflib_SObjectDescribeTest.cls#L49)):*
> ```vb6
> 		System.Assert.isNull(fflib_SObjectDescribe.getDescribe(nullType));
> 		System.Assert.isNull(fflib_SObjectDescribe.getDescribe(nullDescribe));
> 		System.Assert.isNull(fflib_SObjectDescribe.getDescribe(nullSObject));
> ```

Should all of these use the `Assert.areEqual(null, ...)` pattern too?  I cannot see how they would ever be insufficient, BUT ...

**Comment by chazwatkins** [comment]
> > _[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/436)_ status: 0 of 40 files reviewed, 1 unresolved discussion (waiting on @chazwatkins and @daveespo)
> 
> _[`sfdx-source/apex-common/test/classes/fflib_SObjectDescribeTest.cls` line 49 at r3](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/436#-NIUHpU--9Q6YpjJw6QQ:-NIUHpU--9Q6YpjJw6QR:b8u6t83) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/7dad734dc470ab770591b7633f8afba92d7078c0/sfdx-source/apex-common/test/classes/fflib_SObjectDescribeTest.cls#L49)):_
> 
> > ```vbnet
> > 		System.Assert.isNull(fflib_SObjectDescribe.getDescribe(nullType));
> > 		System.Assert.isNull(fflib_SObjectDescribe.getDescribe(nullDescribe));
> > 		System.Assert.isNull(fflib_SObjectDescribe.getDescribe(nullSObject));
> > ```
> 
> Should all of these use the `Assert.areEqual(null, ...)` pattern too? I cannot see how they would ever be insufficient, BUT ...

Yes, they should be.  Thanks for catching that.  I double-checked for other `isNull` and `isNotNull` occurrences and updated them to `areEqual(null, ...)` and `areNotEqual(null, ...)`

**Comment by anuragoyar** [comment]
# Potential Risks and Suggestions:

1.  
File: sfdx-source/apex-common/main/classes/fflib_SObjectDomain.cls  
Code Snippet: System.assertEquals(null, someState); -> System.Assert.areEqual(null, someState);  
Comment: The code is being updated to use the newer System.Assert class methods instead of the deprecated System.assertEquals methods. This is a good practice as it follows Salesforce's recommendation for using the newer assertion methods.

2.  
File: sfdx-source/apex-common/test/classes/fflib_ApplicationTest.cls  
Code Snippet: System.assert(false, 'Expected exception'); -> System.Assert.fail('Expected exception');  
Comment: The code is being updated to use System.Assert.fail() which is more appropriate for testing expected exceptions than using System.assert(false). This improves code readability and follows best practices.

## Summary:

This pull request primarily updates the API version of Salesforce metadata files from 55.0 to 56.0 and modernizes the test assertion methods in Apex test classes. The changes include:

1. Updating the API version in sfdx-project.json from 55.0 to 56.0
2. Updating the API version in all Apex class metadata files from 55.0 to 56.0
3. Replacing deprecated assertion methods with their modern equivalents:
   - System.assertEquals() → System.Assert.areEqual()
   - System.assertNotEquals() → System.Assert.areNotEqual()
   - System.assert() → System.Assert.isTrue()
   - System.assert(false, message) → System.Assert.fail(message)
   - System.assert(obj instanceof Class) → System.Assert.isInstanceOfType(obj, Class)

These changes align with Salesforce's best practices for test methods and keep the codebase up-to-date with the latest API version.

The changes are low risk as they:
1. Don't modify any business logic
2. Don't change any object structures or field definitions
3. Don't modify permissions or access controls
4. Only update test assertion syntax and API versions

No additional test coverage is needed as the changes are non-functional and only affect test methods and metadata versions.

This change is suitable for production deployment and represents good maintenance practice to keep the codebase current with Salesforce's latest recommendations.

**Pull request closed without merging**
