### PR TITLE
Fixed Issue#249

### PR DESCRIPTION
**Pull request by bishwambhar-sen**
Fixed test class failure.

### CODE REVIEW

**Comment by wimvelzeboer** [comment]
@bishwambhar-sen It seems that you also added some .idea files, was that on purpose?

**Comment by bishwambhar-sen** [comment]
Nope, those files are supposed to be ignored.

**Comment by stohn777** [comment]
The `idea` files are still in the branch.
image

**Comment by bishwambhar-sen** [comment]
.idea files removed. Kindly review @JAertgeerts @stohn777 @wimvelzeboer

**Comment by afawcett** [comment]
So I think this needs to be fixed holistically for the lib per... https://github.com/apex-enterprise-patterns/fflib-apex-common/pull/246

**Comment by daveespo** [comment]
This was already covered by John's merge on #246

**Pull request closed without merging**
