### PR TITLE
Ability for SObjectUnitOfWork to resolve self-relationships

### PR DESCRIPTION
**Pull request by adtennant**
Added the ability to handle self-relationships, e.g. 

```
fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new Schema.SObjectType[] { Account.SObjectType });             
Account parent = new Account(Name = 'Parent');
uow.registerNew(parent);
uow.registerNew(new Account(Name = 'Child'), Account.ParentId, parent);
uow.registerNew(new Account(Name = 'Child'), Account.ParentId, parent);
uow.commitWork(); // inserts parent, then inserts children
```

This also allows you to process objects in multiple passes, for example:

```
fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new Schema.SObjectType[] { Account.SObjectType, Custom__c.SObjectType, Account.SObjectType });             
Account parent = new Account(Name = 'Parent');
uow.registerNew(parent);

Custom__c custom = new Custom__c();
uow.registerNew(custom, Custom__c.ParentAccountId__c, parent);

Account child = new Account(Name = 'Child');
uow.registerNew(child, Account.ParentId, parent);
uow.registerRelationship(child, Account.CustomId__c, custom);
uow.commitWork(); // inserts parent, then custom, then finally child
```

This is massively hack-y at the moment, but it works... just about. I'm submitting this pull request early to expose the code to more eyes and to get input on to how I should develop this further. **This is NOT production ready**, it's pre-pre-alpha at best.

Known issues:
- Relies on fiddling with the Id field pre-insert, I can't find a better way of doing this whilst still allowing the public interface to work with SObjects
- Relies on a custom hashmap implementation to remain performant (although this is due to what I suspect is a platform bug, this reliance can be removed when this is fixed, see: http://salesforce.stackexchange.com/q/46525/5460)
- No error handling, e.g. no reporting of objects whose relationships cannot be resolved, they are just never inserted
- Currently no additional tests

### CODE REVIEW

**Comment by afawcett** [comment]
@adtennant Wondering what your latest thoughts are on this?

**Comment by adtennant** [comment]
@afawcett Unfortunately I've still not had a good chunk of time to look at this. It's on my list, it just keeps getting shunted down.

**Comment by afawcett** [comment]
Ok, understood, thanks for the update. If your cool with leaving this open. I am. You never know it might attract the attention of others to help out! :+1:

**Comment by maximorojr** [comment]
I'm needing to commit self-relationships too. Any news about that? Is there an workaround at this moment? Can I help with something?

**Comment by afawcett** [comment]
Folks take a look at this https://github.com/financialforcedev/fflib-apex-common/pull/80. Interested in your views on it both if it suites your needs and implementation. 

@adtennant @maximorojr

**Comment by afawcett** [comment]
I am recommending we close this incomplete PR and focus on https://github.com/financialforcedev/fflib-apex-common/pull/195 to provide this facility. Thank you @adtennant for supporting discussion and thoughts on what seems to be a key feature need for UOW. Please join the discussion on the other PR! 👍   cc @stephenwillcock @agarciaodeian

**Pull request closed without merging**
