### PR TITLE
Add methods and unit test coverage to fflib_SObjects domain

### PR DESCRIPTION
**Pull request by wimvelzeboer**
Thanks for merging the new domain structure!

As mentioned earlier I have a few extra methods for the domain class, a few more test for beter code coverage and some added apex-docs comments

---
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330)

### CODE REVIEW

**Comment by wimvelzeboer** [comment]
@ImJohnMDaniel @daveespo 
Could you have a look at this PR? This will complete the domain class methods.
I wanted to add them earlier into the new domain structure change, but didn't want to keep on adding changes to that already large PR.

**Review by daveespo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330)* status: 0 of 37 files reviewed, 1 unresolved discussion (waiting on @daveespo and @wimvelzeboer)

___
*[sfdx-source/apex-common/main/classes/fflib_SObjects.cls, line 260 at r9](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330#-MzuOPVNAR0shhiGARkQ:-MzuOPVNAR0shhiGARkR:b-7mt6tg) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/00489148bbdd5697dad5893fe247cdc0d3a0c7a1/sfdx-source/apex-common/main/classes/fflib_SObjects.cls#L260)):*
> ```VBA
> 			for (SObjectField sObjectField : sObjectFields)
> 			{
> 				if (String.isNotBlank((String) record.get(sObjectField)))
> ```

Is this change intentional? It appears to be returning objects with NOT blank fields

**Comment by wimvelzeboer** [comment]
> Is this change intentional? It appears to be returning objects with NOT blank fields

@daveespo That is indeed not correct. Its now fixed!

**Review by daveespo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330)* status: 0 of 37 files reviewed, 5 unresolved discussions (waiting on @daveespo and @wimvelzeboer)

___
*[sfdx-source/apex-common/main/classes/fflib_SObjects.cls, line 164 at r12](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330#-N-37ltD1gqatMhnEmGy:-N-37ltD1gqatMhnEmGz:b-7lhgqv) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/6f67e80df025e7c17375b18b356b6dca02760767/sfdx-source/apex-common/main/classes/fflib_SObjects.cls#L164)):*
> ```VBA
> 	 */
> 	@TestVisible
> 	protected Set<Id> getIdFieldValues(Schema.SObjectField sObjectField)
> ```

There doesn't apepar to be any test coverage of this method in this PR

Second, it's poor practice to name a variable the same as a Type -- there are too many places you can end up with weird compiler errors because it can't distinguish between the Type and the instance variable. Please do what you did in the method above and name the SObjectField argument variable `field` for this method and all of the ones below it (see https://github.com/pmd/pmd/issues/2322#issuecomment-640569931 if you need some color on why this is poor practice)

Additionally, these 3 new convenience methods are not DRY .. I think a DRYer pattern would be something like

```
protected Set<Id> getIdFieldValues(SObjectField field){
  Set<Id> result = new Set<Id>;
  populateValueSet(field, result);
  return result;
}

... same pattern for getStringFieldValues and getFieldValues

protected void populateValueSet(SobjectField field, Set<Object> valueSet){
  for(Sobject record : getRecords(){
    result.add(record.get(field);
  }
}
```
___
*[sfdx-source/apex-common/test/classes/fflib_SObjectsTest.cls, line 80 at r12](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330#-N-37b3RADjcSmlsRwoI:-N-37b3RADjcSmlsRwoJ:b-prcj1o) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/6f67e80df025e7c17375b18b356b6dca02760767/sfdx-source/apex-common/test/classes/fflib_SObjectsTest.cls#L80)):*
> ```VBA
> 		Set<Id> recordIds = new Set<Id> {idA, idB, idC};
> 		System.assert(
> 				domain.getRecordIds().containsAll(recordIds),
> ```

s/b equals() not containsAll() ?
___
*[sfdx-source/apex-common/test/classes/fflib_SObjectsTest.cls, line 85 at r12](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330#-N-37eTw1R5fBgHboBGz:-N-37eTw1R5fBgHboBH-:buo9nmt) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/6f67e80df025e7c17375b18b356b6dca02760767/sfdx-source/apex-common/test/classes/fflib_SObjectsTest.cls#L85)):*
> ```VBA
> 
> 		System.assert(
> 				domain.getIdFieldValues(Schema.Account.Id).containsAll(recordIds),
> ```

Same here
___
*[sfdx-source/apex-common/test/classes/fflib_SObjectsTest.cls, line 137 at r12](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330#-N-37Udh9x2g-HscXQBr:-N-37UdiCGCwNoA4VZiI:b-je2miy) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/6f67e80df025e7c17375b18b356b6dca02760767/sfdx-source/apex-common/test/classes/fflib_SObjectsTest.cls#L137)):*
> ```VBA
> 		System.assert(
> 				domain.getStringFieldValues(Schema.Account.ShippingCountry)
> 						.containsAll(
> ```

Shouldn't this be a straight up .equals() not a .containsAll()?
___
*[sfdx-source/apex-common/test/classes/fflib_SObjectsTest.cls, line 149 at r12](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330#-N-37Y9A24uvcLPYJ5-L:-N-37Y9A24uvcLPYJ5-M:b-ya81ng) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/6f67e80df025e7c17375b18b356b6dca02760767/sfdx-source/apex-common/test/classes/fflib_SObjectsTest.cls#L149)):*
> ```VBA
> 		System.assert(
> 				domain.getFieldValues(Schema.Account.ShippingCountry)
> 						.containsAll(
> ```

Same as above

**Comment by wimvelzeboer** [comment]
> Second, it's poor practice to name a variable the same as a Type -- there are too many places you can end up with weird compiler errors because it can't distinguish between the Type and the instance variable. Please do what you did in the method above and name the SObjectField argument variable `field` for this method and all of the ones below it (see [pmd/pmd#2322 (comment)](https://github.com/pmd/pmd/issues/2322#issuecomment-640569931) if you need some color on why this is poor practice)

Yeah, that it true when method become long. I typically have short methods and then these issues typically do not occur.
But I have changed all `sObjectField` variable names into `field`.

> Additionally, these 3 new convenience methods are not DRY .. I think a DRYer pattern would be something like

I have been puzzling with this for a while, but Apex is a bit limited in casting a `Set<Id>` to `Set<Object>`, and visa-versa. Your example with the `populateValueSet` looks very nice, and I would love to implement it, but it does not compile. 
```
protected Set<Id> getIdFieldValues(Schema.SObjectField field)	{
	Set<Id> result = new Set<Id>();
	populateValueSet(field, result);
	return result;
}
protected void populateValueSet(Schema.SObjectField field, Set<Object> valueSet) {
	for (SObject record : getRecords())
	{
		valueSet.add(record.get(field));
	}
}
```
This throws the compile error: 
`Method does not exist or incorrect signature: void populateValueSet(Schema.SObjectField, Set<Id>) from the type fflib_SObjects (167:3)`
I have tried other variants where I used a similar method like `populateValueSet`. got a Set<Object> returned, then iterated over that set to cast every single item to the desired type.
Maybe I missing something but I have not been able to cast `Set<Object>` to `Set<Id>`.
That's is why I ended up with this, not to nice indeed, NON-DRY solution. But at least it is faster and it still does avoid tons more of iterations in project/application/domain code.
@daveespo Any other thoughts on this on how to solve it? 

> Shouldn't this be a straight up .equals() not a .containsAll()? 

That makes more sense indeed! Its modified!

**Comment by wimvelzeboer** [comment]
@daveespo And another thought, the whole reason to add these methods like `getIdFieldValues`, is that we are unable to cast `Set<Object>` to `Set<Id>`. 
If we could have done that, then we could simply write a domain method like the following:
```
public Set<Id> getAccountIds()
{
	return (Set<Id>) getFieldValues(Schema.Contact.AccountId);
}
```
If this was possible we wouldn't need all those extra getXXXFieldValues() methods.

**Review by daveespo — APPROVED** [review]
> Reviewed 3 of 4 files at r7, 32 of 33 files at r8, 2 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wimvelzeboer)

___
*[sfdx-source/apex-common/main/classes/fflib_SObjects.cls, line 164 at r12](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330#-N-37ltD1gqatMhnEmGy:-N-OAjql1AtcTUTEuy6F:b-t8z5jt) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/6f67e80df025e7c17375b18b356b6dca02760767/sfdx-source/apex-common/main/classes/fflib_SObjects.cls#L164)):*
<details><summary><i>Previously, daveespo (David Esposito) wrote…</i></summary><blockquote>

There doesn't apepar to be any test coverage of this method in this PR

Second, it's poor practice to name a variable the same as a Type -- there are too many places you can end up with weird compiler errors because it can't distinguish between the Type and the instance variable. Please do what you did in the method above and name the SObjectField argument variable `field` for this method and all of the ones below it (see https://github.com/pmd/pmd/issues/2322#issuecomment-640569931 if you need some color on why this is poor practice)

Additionally, these 3 new convenience methods are not DRY .. I think a DRYer pattern would be something like

```
protected Set<Id> getIdFieldValues(SObjectField field){
  Set<Id> result = new Set<Id>;
  populateValueSet(field, result);
  return result;
}

... same pattern for getStringFieldValues and getFieldValues

protected void populateValueSet(SobjectField field, Set<Object> valueSet){
  for(Sobject record : getRecords(){
    result.add(record.get(field);
  }
}
```



</blockquote></details>

Yeah, my bad on suggesting that a Set<Object> could be used generically .. silly me and thinking that Apex behaved as one would expect :-/

I'm resolving this thread as satisfactory

**Review by stohn777 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330)* status: all files reviewed, 1 unresolved discussion (waiting on @ImJohnMDaniel and @wimvelzeboer)

___
*[sfdx-source/apex-common/main/classes/fflib_Objects.cls, line 104 at r13](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330#-N-noKq4684OCQhUPxsT:-N-noKq52cLYrkI_g2WW:b-ckik1i) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/fbc113f1d026bc10bdc703871c4e9dff5c90b307/sfdx-source/apex-common/main/classes/fflib_Objects.cls#L104)):*
> ```VBA
> 	}
> 
> 	public Object getFirstObject()
> ```

What is the reasoning behind this method?  Apex does not provide a "getFirst...()" method for the List class.

**Review by stohn777 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330)* status: all files reviewed, 1 unresolved discussion (waiting on @ImJohnMDaniel and @wimvelzeboer)

___
*[sfdx-source/apex-common/main/classes/fflib_Objects.cls, line 104 at r13](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330#-N-noKq4684OCQhUPxsT:-N0Mp_b6Dp4dwGbiFM_Q:bonebl3) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/fbc113f1d026bc10bdc703871c4e9dff5c90b307/sfdx-source/apex-common/main/classes/fflib_Objects.cls#L104)):*
<details><summary><i>Previously, stohn777 (John Storey) wrote…</i></summary><blockquote>

What is the reasoning behind this method?  Apex does not provide a "getFirst...()" method for the List class.
</blockquote></details>

Apex Commons is a foundation on which teams can build their implementations, including more convenient methods.  I'm opposed to this being herein.

**Comment by wimvelzeboer** [comment]
> Apex Commons is a foundation on which teams can build their implementations, including more convenient methods. I'm opposed to this being herein.

Sure, no problem. I removed the method!

**Review by stohn777 — APPROVED** [review]
> Reviewed 2 of 2 files at r13, 3 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330)* status: all files reviewed, 1 unresolved discussion (waiting on @daveespo, @ImJohnMDaniel, and @wimvelzeboer)

**Review by daveespo — APPROVED** [review]
> Reviewed 3 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/330)* status: all files reviewed, 1 unresolved discussion (waiting on @ImJohnMDaniel and @wimvelzeboer)

**Pull request merged**
