### PR TITLE
Update fflib_SObjectSelector.cls

### PR DESCRIPTION
**Pull request by Javwad**
I think we can remove getSObjectType2() method and replace it with getSObjectType();

### CODE REVIEW

**Comment by ImJohnMDaniel** [comment]
The fflib_SObjectSelectorTest.cls class would also need to be updated for this PR to be approved.

**Comment by Javwad** [comment]
> The fflib_SObjectSelectorTest.cls class would also need to be updated for this PR to be approved.
@ImJohnMDaniel 
Updated fflib_SObjectSelectorTest.cls - replaced getSObjectType2() with getSObjectType(). I have checked in test class that we are using a child selector class which has extended the fflib_SObjectSelector class. Hence, test class will not throw "Method is not visible. - error"

**Comment by Javwad** [comment]
> I don't understand the original intent of the getSObjectType2() method. I reviewed the work that originally created the method ([ec45ada](https://github.com/apex-enterprise-patterns/fflib-apex-common/commit/ec45ada13232acd69277daa8c8f3dacd2d1e29df)) and I'm wondering if it has something to do with masking .. i.e. there's an `sObjectType()` method and a `getSObjectType()` abstract method -- perhaps `getSObjectType()` can't be mocked and the `getSObjectType2()` is the way around that. This code all predates the introduction of the native Apex mocking framework so perhaps it's no longer necessary.
> 
> In short, I don't feel confident approving this PR.
> 
> @Javwad -- what problem are you trying to solve with this proposed change?

@daveespo I have the same question on the original intent of the method. I guess it's because we cannot call an abstract method from an abstract class. However, I am not facing any problem, it just seems like an additional step or piece of code which I believe we can remove.

**Comment by ImJohnMDaniel** [comment]
@afawcett and @ca_peterson -- do either of you know the history of this `getSObjectType2()` method?

**Comment by afawcett** [comment]
@Javwad @daveespo good detective work! It took me a few mins but yes, i do believe it was a way to access the selectors sobjecttype in a generic way when working with mocking. Per the comment on it it was done because elevating the abstract method to public appeared to have broken at the time the backwards compatibility of the class. Regardless though, there does appear to be a number of folks using this method (at least having done a global GitHub search). So if we are to maintain public API backwards compat even if its a bit less than ideal, we should probably just ignore this itch. https://github.com/search?q=getSObjectType2&type=Code

**Comment by daveespo** [comment]
Good thinking with the Github search @afawcett  -- definitely not worth rocking the boat here

**Pull request closed without merging**
