### PR TITLE
Enable Apex Commons for (free) Continuous Quality Metrics with Code Climate

### PR DESCRIPTION
**Pull request by rsoesemann**
**This pull request only adds a few configuration files to this repository to allow Continuous Code Analysis with the [Code Climate platform](https://codeclimate.com/features).**

Code Climate [integrate tightly into Github](https://codeclimate.com/browser-extension) and validates code on every commit or pull-request. Code Climate is [free forever for Open source repos](https://codeclimate.com/oss) and works instantly without even creating a code climate account.

We (a bunch of Salesforce developers working for Salesforce.com ISV Up2Go) recently built an [open source validation engine](https://github.com/Up2Go/codeclimate-apex) for Apex classes and triggers (based on the [famous Java tool PMD](http://pmd.github.io/)). We now want to make it known and accessible for as many projects as possible. We believe that not only private companies can improve their code base by continuous automatic code analysis but also Open source projects.

This is how Milestone PM would look like:

**GitHub UI ([using the Chrome extension](https://codeclimate.com/browser-extension)) showing overall grades per class and trigger:**
bildschirmfoto 2016-05-25 um 10 47 12

**Rule violations shown in the Github source view ([using the Chrome extension](https://codeclimate.com/browser-extension)):**
bildschirmfoto 2016-05-25 um 10 47 27

**The repo's Feed shows how code quality improves or degrades over time and where**
bildschirmfoto 2016-05-25 um 10 28 31

_Disclaimer: We are not connected to Code Climate in any way. This is not a commercial product of Up2Go but only a hobby sideproject of it's developers. We are just doing this for fun and to spread **[Clean Code](https://www.pluralsight.com/blog/software-development/7-reasons-clean-code-matters)** in the Salesforce.com developer community. We don't get any money for our engagement._

### CODE REVIEW

**Comment by afawcett** [comment]
Thanks @up2go-rsoesemann for this, i'm keen to adopt this new innovation you have brought to the community. Thanks for helping us along with adopting it. I'd like to also take some time to review the rule set you've attached. This will likely be in the coming weeks though. Lets see if we can for sure get this done for Dreamforce at the very latest! 👍

**Comment by up2go-rsoesemann** [comment]
@afawcett Still interested in integrating PMD into your public repos using the ApexMetrics Code Climate engine?

**Comment by afawcett** [comment]
Yes still interested. 👍

**Comment by up2go-rsoesemann** [comment]
I recently helped Codacy (another Github integrated code checker) to understand Apex Code. So there is an Alternative to Code Climate. I personally prefer Code Climate for Open Source Projects as they directly show grades and issues in Github using browser plugins.

**Pull request closed without merging**
