### PR TITLE
Suggestion for CriteriaBuilder

### PR DESCRIPTION
**Pull request by clebrsonn**
added criteriabuilder, junction predicate and predicate for create conditions in where and return in string

- - -
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/458)

### CODE REVIEW

**Comment by stohn777** [comment]
Interestingly following.  Unit tests?

**Comment by clebrsonn** [comment]
> Interestingly following.  Unit tests?

I'm finishing unit tests. Do you have some ideas for scenario?

**Comment by stohn777** [comment]
> I'm finishing unit tests. Do you have some ideas for scenario?

`fflib_CriteriaBuilderTest` class focusing on the output of the `toSoql()` method.

**Comment by stohn777** [comment]
As I'm sure you know, this SF Developer topic is likely the canonical reference for the Where-Clause specs.

[1] https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_conditionexpression.htm

**Comment by clebrsonn** [comment]
> As I'm sure you know, this SF Developer topic is likely the canonical reference for the Where-Clause specs.
> 
> [1] https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_conditionexpression.htm

Thanks, I'll verify.

**Comment by clebrsonn** [comment]
@stohn777 I finished the adjustments for the most common cases of where conditions.
I based on hibernate and the two open PR's below:

 [393](https://github.com/apex-enterprise-patterns/fflib-apex-common/pull/393), [313](https://github.com/apex-enterprise-patterns/fflib-apex-common/pull/313)

The scenarios that are not 100% yet is when using a subquery, i don't know how would be the best way to treat this scenario.

these scenarios are covered in the methods below:
notInCriteriaForSubSelect
inCriteriaForSubSelect

I thought about not allowing this scenario, and if I want to do the same I would use the old conditions just adding Predicates for each select

**Comment by daveespo** [comment]
See #483

**Pull request closed without merging**
