### PR TITLE
Issue #437 - Unit test failure in multi-currency org

### PR DESCRIPTION
**Pull request by stohn777**
Pass selector's SObjectType to QueryFactory.
- Supporting test and improvement

https://github.com/apex-enterprise-patterns/fflib-apex-common/issues/437

- - -
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/438)

### CODE REVIEW

**Review by daveespo — DISMISSED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/438)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ImJohnMDaniel)

**Review by ImJohnMDaniel — APPROVED** [review]

**Review by ImJohnMDaniel — DISMISSED** [review]

**Review by edgarrelh — APPROVED** [review]

**Comment by stohn777** [comment]
Updated to 'master' and resolved merge conflicts.
Attn:  @daveespo, @ImJohnMDaniel

**Review by daveespo — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/438)* status: all files reviewed, 2 unresolved discussions (waiting on @stohn777)

___
*[`sfdx-source/apex-common/test/classes/fflib_SObjectSelectorTest.cls` line 741 at r3](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/438#-N_0d8NfBnWhjy7q8kDc:-N_0d8NfBnWhjy7q8kDd:b-milf0v) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/dbda661a3a81fc350d14cb737016ca3bc49ec4ac/sfdx-source/apex-common/test/classes/fflib_SObjectSelectorTest.cls#L741)):*
> ```vb6
> 		expectedSelectFields.add('id');
> 		expectedSelectFields.add('status');
> 		if (UserInfo.isMultiCurrencyOrganization()) expectedSelectFields.add('currencyisocode');
> ```

Please use curly braces (here and the 2 other below) -- I patched up some legacy lack of curly braces when refactoring for User Mode .. there are plenty of violations of this rule but let's not expand the violations 
___
*[`sfdx-source/apex-common/test/classes/fflib_SObjectSelectorTest.cls` line 793 at r3](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/438#-N_0cOU_Dd4vX5kmdMLl:-N_0cOU_Dd4vX5kmdMLm:bhpa3ma) ([raw file](https://github.com/apex-enterprise-patterns/fflib-apex-common/blob/dbda661a3a81fc350d14cb737016ca3bc49ec4ac/sfdx-source/apex-common/test/classes/fflib_SObjectSelectorTest.cls#L793)):*
> ```vb6
> 	}
> 
> 	private class Testfflib_GroupSelector extends fflib_SObjectSelector {
> ```

We have a mix of these inner classes naming conventions here -- I don't see much reason to continue the legacy prefixing with `Testfflib_` since it's an inner private class I don't think there's a risk of it resolving to a class of the same name outside of this test class. The new Selectors I added for the User Mode stuff don't use the Testfflib prefix.

**Review by daveespo — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/438)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stohn777)

**Review by ImJohnMDaniel — APPROVED** [review]

**Pull request merged**
