### PR TITLE
Update fflib_SecurityUtils.cls and fflib_SObjectUnitOfWork.cls with DEFFERED Enum

### PR DESCRIPTION
**Pull request by Javwadazeem**
Enable Improved Caching of Org Schema Critical Update
Replaced getDescribe() method with getDescribe(Object options).
DEFFERED mode is useful when we do not need child relationships.
Note- By default, unless the Critical Update is enabled, all child relationships are eagerly loaded.

### CODE REVIEW

**Comment by Javwadazeem** [comment]
Updated fflib_SecurityUtils & fflib_SObjectUnitOfWork with getDescribe(Object options) method.

**Comment by Javwadazeem** [comment]
@afawcett , @daveespo & @ImJohnMDaniel could you please buy sometime out of you busy schedule and review this PR?

**Comment by Javwadazeem** [comment]
I have another suggestion, I think we can replace all of the statements where we are using `SobjectType.getDescribe().getName()` to just get the SObject String Name with `String.valueOf(SobjectType)`.

**Comment by ImJohnMDaniel** [comment]
@Javwadazeem can you bring your fork up to date please with the main repo?  Specifically, the main repo is now in DX Source Format.  Currently the fflib_SObjectUnitOfWork and fflib_SecurityUtils classes are showing conflict.

**Comment by Javwadazeem** [comment]
> @Javwadazeem can you bring your fork up to date please with the main repo? Specifically, the main repo is now in DX Source Format. Currently the fflib_SObjectUnitOfWork and fflib_SecurityUtils classes are showing conflict.

@ImJohnMDaniel , I have updated my fork. Could you please have a look? Thank you.

**Comment by ImJohnMDaniel** [comment]
@afawcett or @daveespo -- thoughts?

**Comment by stohn777** [comment]
Ticket states "Update fflib_SecurityUtils.cls" but also includes changes to fflib_SObjectUnitOfWork.cls.  Is this okay?  I think the virtualization of UoW is either done already or pending -- don't remember offhand.

**Comment by daveespo** [comment]
I don't generally object to this PR but SF changed the auto-enforcement date of the CRUC from August 2021 to August 2020:

https://releasenotes.docs.salesforce.com/en-us/summer20/release-notes/rn_apex_enable_improved_schema_caching.htm

This code change is no longer necessary, IMO

@ImJohnMDaniel @afawcett

**Comment by daveespo** [comment]
Since this is now the default behavior for `getDescribe`, we no longer need the changes suggested in this PR

Thank you for your contribution though!

**Pull request closed without merging**
