### PR TITLE
Added more test cases

### PR DESCRIPTION
**Pull request by fransf-wtax**
Added more test cases to fflib_SObjectSelectorTest and fflib_SObjectUnitOfWorkTest to get coverage for fflib_SObjectSelector and fflib_SObjectUnitOfWork to 75%.

---
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/366)

### CODE REVIEW

**Review by wimvelzeboer — DISMISSED** [review]

**Comment by fransf-wtax** [comment]
Anyone else that can review this? @daveespo ?

**Comment by AlexSutherlandLiberty** [comment]
Hey @ImJohnMDaniel @stohn777 @daveespo, think we can get this review and approval prioritized/accelerated? ;-) Kind of an embarrassing shortcoming in this library...

**Comment by ImJohnMDaniel** [comment]
@fransf-wtax, I have been looking at your branch and the changes look good.  Having said that, I need to you update your PR branch with the latest before we can approve and merge it to the main code base.

**Comment by fransf-wtax** [comment]
@ImJohnMDaniel I've rebased on master. Don't know if the tests now still provide >75% coverage, but I can always submit a new PR if that's not the case anymore. Thanks!

**Review by ImJohnMDaniel — APPROVED** [review]
@fransf-wtasx, thanks for the update.  The improvement in coverage does remain.  Thanks for the addition.  Always appreciated.  Cheers!

**Pull request merged**
