### PR TITLE
switched to `apex-enterprise-patterns/setup-sfdx@v2`

### PR DESCRIPTION
**Pull request by ImJohnMDaniel**
This change is [Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/474)

### CODE REVIEW

**Review by daveespo — DISMISSED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/474)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stohn777)

**Review by daveespo — APPROVED** [review]
Since I already approved this once, I'm not going to go back and backtrack on the approval. But I'm not sure why you'd add the YAML comments -- they're just noise and code comments come with their own maintenance cost so should be used sparingly -- generally for unidiomatic sections 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/474#-:-Nm0qvd_8CGnSQPFWyx_:bsbr48z)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stohn777)

**Comment by ImJohnMDaniel** [comment]
@daveespo, I have found the comments make it easier to read.  I admit that it is a matter of opinion but that is the reason.

**Review by daveespo — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/apex-enterprise-patterns/fflib-apex-common/474)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stohn777)

**Pull request merged**
