### PR TITLE
Rename README.md to .markdown to FIX trail module

### PR DESCRIPTION
**Pull request by Maximetinu**
Hi!

When trying to deploy fflib apex common to my Trailhead Playground, it throwed the next error:

```
Deployment Started
Status: Queued
Status: Completed
Deployment Complete
Failures:
customMetadata/README.md(1,1):Error parsing file: Content is not allowed in prolog.
```

It is fixed by renaming the file to README.markdown, which is still shown by GitHub as a markdown styled readme at the repository root folder page

### CODE REVIEW

**Comment by wimvelzeboer** [comment]
Wouldn't it be better to add the file to an ignore file instead of renaming the file extension? README.md is the standard naming convention.

**Comment by Maximetinu** [comment]
> Wouldn't it be better to add the file to an ignore file instead of renaming the file extension? README.md is the standard naming convention.

I tried to ignore it by using a .forceignore file but it didn't work. Do you know any other way to ignore files on deployment?

**Comment by ImJohnMDaniel** [comment]
@Maximetinu -- Can you provide an example of how you listed the README.md file in the `.forceignore` file?

**Comment by ImJohnMDaniel** [comment]
Oh wait.  This issue is a duplicate of apex-enterprise-patterns/fflib-apex-mocks#84

**Comment by ImJohnMDaniel** [comment]
Based on the fact that this is a duplicate of the apex-enterprise-patterns/fflib-apex-mocks#84 issue, I am closing this PR.

**Pull request closed without merging**
